### ISSUE TITLE
blogo is not running?

### ISSUE THREAD

**Issue by alfonsop123** [pluja/blogo#16]
when i check localhost:3000 or 127.0.0.1:3000 it does not work...

alfonsop123@raspberrypi:~ $ nano docker-compose.yml
alfonsop123@raspberrypi:~ $ docker compose up -d
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dalfonsop123%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
alfonsop123@raspberrypi:~ $ sudo docker compose up -d
[+] Running 2/2
 ✔ Network alfonsop123_default  Created                                    0.2s
 ✔ Container blogo              Started                                    0.3s
alfonsop123@raspberrypi:~ $ sudo docker compose up -d
[+] Running 1/0
 ✔ Container blogo  Started                                                0.0s
alfonsop123@raspberrypi:~ $

**Comment by alfonsop123** [comment]
i followed what it said in readme

**Comment by alfonsop123** [comment]
Just checked logs by using sudo docker logs blogo and found that its full of exec /app/blogo: exec format error...

**Comment by ItsRaelx** [comment]
try with sudo or add user to docker group

**Comment by ItsRaelx** [comment]
Hi @alfonsop123 ,
This is error with docker itself not our configuration. There are several ways to fix this but the easiest is to:
1. Add user to docker group and then try running command again:
```
sudo usermod -aG docker $USER
```
> After running `usermod` log out of the terminal and log in again (or just reboot)

2. If previous command doesn't work just use root by running command with sudo:
```
sudo docker compose up -d
```

I hope this helps!

**Comment by ItsRaelx** [comment]
I just tested the exact same steps as in README.md and it works for me. When i get home i will try to run this on my rasberypi.

**Comment by alfonsop123** [comment]
Ty, I did it I will check if it's running on port 3000 :D

**Comment by alfonsop123** [comment]
Nooooo bad gateway 502

**Comment by alfonsop123** [comment]
alfonsop123@raspberrypi:~ $ sudo usermod -aG docker alfonsop123
alfonsop123@raspberrypi:~ $ docker compose down
[+] Running 2/2
 ✔ Container blogo              R...                   0.0s  ✔ Network alfonsop123_default  Removed                0.3s alfonsop123@raspberrypi:~ $ sudo docker compose up -d
[+] Running 2/2
 ✔ Network alfonsop123_default  Created                0.1s  ✔ Container blogo              S...                   0.3s alfonsop123@raspberrypi:~ $

**Comment by ItsRaelx** [comment]
> alfonsop123@raspberrypi:~ $ sudo usermod -aG docker alfonsop123 alfonsop123@raspberrypi:~ $ docker compose down [+] Running 2/2 ✔ Container blogo R... 0.0s ✔ Network alfonsop123_default Removed 0.3s alfonsop123@raspberrypi:~ $ sudo docker compose up -d [+] Running 2/2 ✔ Network alfonsop123_default Created 0.1s ✔ Container blogo S... 0.3s alfonsop123@raspberrypi:~ $

Still it doesn't work? 502 error seems weird, are you sure you have nothing else on that port? can you show your docker-compose.yml?

**Comment by ItsRaelx** [comment]
And can you check those logs? You can try running docker compose without "-d" flag

**Comment by alfonsop123** [comment]
Yeah, nothing else on port 3000
services:
  blogo:
    image: pluja/blogo:latest
    container_name: blogo
    restart: unless-stopped
    volumes:
      - ./articles:/app/articles
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # CONFIG
      BLOGO_TITLE: Blogo
      BLOGO_DESCRIPTION: A blog built with Blogo!
      BLOGO_KEYWORDS: blog,open source
      BLOGO_URL: http://localhost:3000
      #BLOGO_ANALYTICS: '<script defer src="https://my.analytics.site/script.js"></script>'
      TIMEZONE: UTC

      # NOSTR CONFIG
      PUBLISH_TO_NOSTR: false
      #NOSTR_NSEC: ""
      #NOSTR_RELAYS: "wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"
And I'll try running it like that without -d

**Comment by alfonsop123** [comment]
alfonsop123@raspberrypi:~ $ docker compose down
[+] Running 2/2
 ✔ Container blogo              R...                   0.0s  ✔ Network alfonsop123_default  Removed                0.3s alfonsop123@raspberrypi:~ $ docker compose up
[+] Running 1/2
 ✔ Network alfonsop123_default  Created                0.1s  ⠹ Container blogo              C...                   0.2s Attaching to blogo
blogo  | exec /app/blogo: exec format error
blogo exited with code 0
alfonsop123@raspberrypi:~ $

**Comment by alfonsop123** [comment]
Also sorry for taking long I got the github app but idk how to setup notifications yet I'm nearly doing it lol

**Comment by pluja** [comment]
How are you accessing blogo on the browser?

**Comment by alfonsop123** [comment]
On the rpi4 I'm using localhost:3000 and 127.0.0.1:3000 and then for cloud flare tunnels I put those 2 but none work, cloud flare does not affect the local host btw

**Comment by pluja** [comment]
You can't access blogo locally on your browser in the raspberry pi using 127.0.0.1:3000?

**Comment by alfonsop123** [comment]
But local host you can...

**Comment by alfonsop123** [comment]
This does not really help I think because I'm getting a error exec format thing and it exits with code 0...

**Comment by alfonsop123** [comment]
@ItsRaelx when your not busy, could you try running on your rpi4?

**Comment by ItsRaelx** [comment]
Hi @alfonsop123,
I tried running blogo on my raspberypi 4 with 2GB Ram and it works without an issue!

Steps that i took to get there:
1. Installed RaspberyPi OS (without desktop environment) and connected to my home network
2. Updated the system using `apt update && apt upgrade -y`
3. Installed docker by following [official guide](https://docs.docker.com/engine/install/debian/) for debian
3. Created folder in my home directory and `cd` into it
```bash
mkdir blogo
cd blogo/
```
4. Pasted docker-compose.yml file in this folder
```
services:
  blogo:
    image: pluja/blogo:latest
    container_name: blogo
    restart: unless-stopped
    volumes:
      - ./articles:/app/articles
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      BLOGO_TITLE: Blogo
      BLOGO_DESCRIPTION: A blog built with Blogo!
      BLOGO_KEYWORDS: blog,open source
      BLOGO_URL: http://localhost:3000
      #BLOGO_ANALYTICS: '<script defer src="https://my.analytics.site/script.js"></script>'
      TIMEZONE: UTC
      PUBLISH_TO_NOSTR: false
      #NOSTR_NSEC: ""
      #NOSTR_RELAYS: "wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"
```
> I modified it to run on 0.0.0.0 so i can view this webpage from other computer
5. Run command: `docker compose up -d`

On other computer i typed IP of my raspbery pi with port 3000 (for me it is `192.168.1.5:3000`) and i saw a blogo landing page.

**Comment by alfonsop123** [comment]
wait its supposed to be in localhost:3000 right

**Comment by alfonsop123** [comment]
no ports
alfonsop123@raspberrypi:~/blogo $ docker ps -a
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS                          PORTS     NAMES
e9d15db836f8   pluja/blogo:latest   "/app/blogo -path /a…"   5 minutes ago   Restarting (1) 22 seconds ago             blogo

**Comment by alfonsop123** [comment]
and i also get this :(((

alfonsop123@raspberrypi:~/blogo $ docker logs blogo
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error
exec /app/blogo: exec format error

**Comment by ItsRaelx** [comment]
@alfonsop123 delete all your previous files, create new directory and follow my steps, i cant recreate your issue.

**Comment by alfonsop123** [comment]
Ok, also how do I delete the server installation, and I'll just keep the yml docker compose file

**Comment by ItsRaelx** [comment]
What do you mean? Just delete the folder that you previously created for blogo and create new one and paste my version of docker-compose into it.

**Comment by alfonsop123** [comment]
Oh OK it's cause Before the new Readme file was changed, I downloaded them but idk what directory they download to

**Comment by ItsRaelx** [comment]
@pluja, you can close this issue i think.

**Comment by alfonsop123** [comment]
:( it dont work rip
