### ISSUE TITLE
how to make a article

### ISSUE THREAD

**Issue by alfonsop123** [pluja/blogo#17]
### Feature Description

How do I make a article, I don't get documentation could I get like a example of making one (the command)? 

### Use Case

No

### Code of Conduct

- [X] I have searched for similar feature requests
- [X] I have provided a clear and detailed explanation

**Comment by alfonsop123** [comment]
Only choice I had I could not make a blank one :////

**Comment by pluja** [comment]
Read the Usage section from the readme please.

**Comment by pluja** [comment]
@alfonsop123 

As I mentioned before, the instructions are in the README.md. Here's the command again, which you can find in the Usage section:

````
docker compose exec -it blogo blogo -new my-post-slug
```

**Comment by alfonsop123** [comment]
Ok that .makes more sense ty

**Comment by pluja** [comment]
@alfonsop123 it's the command from the readme 😅

**Comment by alfonsop123** [comment]
Shiz
