### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alfonsop123** [pluja/blogo#19]
### Feature Description

How do I make a article, I don't get documentation could I get like a example of making one (the command)? give me a example of the command I don't get the usage from read me file/docs bruh

### Use Case

No

### Code of Conduct

- [X] I have searched for similar feature requests
- [X] I have provided a clear and detailed explanation

**Comment by pluja** [comment]
Please, stop opening the same issue again and again. Use the first one. You can still comment even if it's closed.
