### ISSUE TITLE
no entry point error

### ISSUE THREAD

**Issue by Stefanistkuhl** [pluja/blogo#8]
so i tried to run it on a debian vm and got 

steps to reproduce:
1. run the 2 mentioned commands to selfhost

```docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-d": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container:
```
so then i tried it with docker compose and the logs say this:
`exec /app/blogo: exec format error`

when i check the container in portainer it says null.

edit: i fixed this by adding 
`ENTRYPOINT ["app/blogo"]`
to the dockerfile

**Comment by pluja** [comment]
Hi, could you try pulling the latest version and running:

```
docker run \
  --name blogo \
  --env-file .env \
  --volume $(pwd)/articles:/app/articles \
  --publish 3000:3000 \
  --detach \
  pluja/blogo:latest
```

(or the latest docker-compose.yml file)

**Comment by Stefanistkuhl** [comment]
still the same outcome with `exec /app/blogo: exec format error` not found

**Comment by pluja** [comment]
Hi, I am unable to replicate your issue. I do exactly this:

1.Create a new directory: `mkdir /tmp/blogo && cd /tmp/blogo`
2. Get the `.env` file:

```
docker run \
  --name blogo \
  --env-file .env \
  --volume $(pwd)/articles:/app/articles \
  --publish 3000:3000 \
  --detach \
  pluja/blogo:latest
```

3. Visit http://localhost:3000 and see blogo running.

Please, make sure you stop and remove any blogo containers, and that you pull the latest blogo image `docker pull pluja/blogo:latest` before testing.

> edited the file and added new md files but none would show up.

Did you make sure the `draft` attribute is set to `false`? if you visit http://localhost:3000/p/the-post-slug can you see your post as a draft?

**Comment by Stefanistkuhl** [comment]
i get a diffrent error now 
```
5:20PM INF Using path: /app
5:20PM WRN No .env file found, using default settings or environment variables.
5:20PM FTL Failed to load timezone location '"UTC"' error="unknown time zone \"UTC\""
```
these were my steps to reproduce:
```
 rm -rf blogo
  851  docker stop blogotest && docker rm blogotest
  852  mkdir blogo
  853  cd blogo/
  854  docker pull pluja/blogo:latest
  855  docker run   --name blogo   --env-file .env   --volume $(pwd)/articles:/app/articles   --publish 3001:3000   --detach   pluja/blogo:latest
  856  wget https://raw.githubusercontent.com/pluja/blogo/main/example.env -O .env
  857  docker run   --name blogo   --env-file .env   --volume $(pwd)/articles:/app/articles   --publish 3001:3000   --detach   pluja/blogo:latest
```

**Comment by pluja** [comment]
I think this is related to the `TIMEZONE` variable in the `.env` file. You should change it to whatever timezone you prefer, for example `Europe/Amsterdam`

**Comment by pluja** [comment]
That's weird, can  you share how are you hosting it? The command / compose file you use.

I tried running locally with the latest version and I am able to use "UTC" as value without issues:

```
[+] Running 0/1
 Container blogo  Recreated                                                                                                              0.4s 
Attaching to blogo-testing
blogo-testing  | 9:45PM INF Using path: /app
blogo-testing  | 9:45PM WRN No .env file found, using default settings or environment variables.
blogo-testing  | 7:45PM INF Loaded settings:
blogo-testing  | 7:45PM INF     ~ Title: Blogo
blogo-testing  | 7:45PM INF     ~ Description: Welcome to Blogo, a light and easy blog. No complicated extras, just a straightforward blog. Now, here's the twist: Blogo can also publish your posts straight to Nostr for backing them up and getting even more reach. Lift your ideas higher!
blogo-testing  | 7:45PM INF     ~ Url: http://localhost:3500
blogo-testing  | 7:45PM INF     ~ Keywords: blog
blogo-testing  | 7:45PM INF     ~ Timezone: UTC
blogo-testing  | 7:45PM INF     ~ Analytics: yes
blogo-testing  | 
blogo-testing  | 7:45PM INF PUBLISH_TO_NOSTR is set to false. Not publishing...
blogo-testing  | 7:45PM INF Starting server on port 3000...
```

**Comment by Stefanistkuhl** [comment]
I used the commands mentioned above but this time i edited to .env file set it to a TZ which i copied from [here](https://docs.diladele.com/docker/timezones.html). I tried it on a rpi4b with pios lite and debian bullseye but tried it on a debian vm aswell with bookworm and got the same err. (I repulled the image ofc)

**Comment by pluja** [comment]
Can you share the variable definition? I think the error is because for some reason, it is trying to use `"UTC"` as the timezone including the `"` symbols:

```error
5:20PM FTL Failed to load timezone location '"UTC"' error="unknown time zone \"UTC\""
```

The correct timezone should be without the `"`

**Comment by Stefanistkuhl** [comment]
`pi@raspberrypi:~/blogo $ cat .env
# CONFIG
BLOGO_TITLE="Blogo"
BLOGO_DESCRIPTION="A blog built with Blogo!"
BLOGO_KEYWORDS="blog,open source"
BLOGO_URL="http://localhost:3000"
BLOGO_ANALYTICS=''
TIMEZONE="Europe/Vienna"

# NOSTR CONFIG
PUBLISH_TO_NOSTR=false
#NOSTR_NSEC=""
#NOSTR_RELAYS="wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"`

**Comment by pluja** [comment]
Can you try removing the `"`?

**Comment by Stefanistkuhl** [comment]
works now thx
